using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MortensWay
{
    internal static class BFS
    {


        public static Tile BFSMethod(Tile startNode, Tile endNode)
        {
            Queue<Edge> stack = new Queue<Edge>();
            Edge startEdge = new Edge(0,startNode, startNode);
            stack.Enqueue(startEdge);

            while (stack.Count > 0)
            {
                if(stack.Count > 10000000)
                {
                    return null;
                }
                Edge edge = stack.Dequeue();
                if (!edge.To.Discovered)
                {
                    edge.To.Discovered = true;
                    edge.To.Parent = edge.From;
                    //Console.WriteLine("Node visited: " + edge.To.Type);
                }
                if (edge.To == endNode)
                {
                    return edge.To;
                }
                foreach (Edge e in edge.To.Edges)
                {
                    if (!e.To.Discovered)
                    {
                        stack.Enqueue(e);
                    }
                }
            }
            return null;

        }
        /// <summary>
        /// Returns a list of tiles, following the path generated by the BFSMethod.
        /// </summary>
        /// <param name="endNode">The tile where the BFS ended</param>
        /// <param name="startNode">The Tile where the BFS started.</param>
        /// <returns></returns>
        public static List<Tile> FindPath(Tile endNode, Tile startNode)
        {
            List<Tile> pathOfNodes = new List<Tile>();
            pathOfNodes.Add(endNode);
            while (endNode != startNode)
            {

                pathOfNodes.Add(endNode.Parent);
                endNode = endNode.Parent;
            }
            pathOfNodes.Reverse();
            return pathOfNodes;
        }


    }

}

